# Site settings
title: Steve Yuen
description: ''
url: 'https://stevewyuen.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Steve Yuen'
  email: steve@stevewyuen.com
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
#  github_username:  steveywp
  linkedin_username:  steve-y

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
